source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

# 使用framework
use_frameworks!

# 忽略警告
inhibit_all_warnings!

# 三方库
def thirdPods

end

# 基础层
def basePods
  # 基础代理
  pod 'LQGBaseAppDelegate'
end

# 工具层
def toolPods
  # 中间件
  pod 'LQGCTMediator'
end

# 业务层
def businessPods
  # 主题
  pod 'LQGUIStyle', :git => 'https://github.com/LuoJianGitHub/LQGUIStyle.git', :tag => '1.0.0'
  
  # 签名
  # pod 'LQGSign', :path => '../../LQGSign'
  pod 'LQGSign', :git => 'https://github.com/LuoJianGitHub/LQGSign.git', :tag => '1.0.0'
  pod 'LQGSign_Category', :path => '../'
end

targets = ['LQGSign_Category_Example']

targets.each do |t|
  target t do
    thirdPods
    basePods
    toolPods
    businessPods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # do your self something
    end
  end
end
